---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: store-front
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: flux
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: aks-store-demo
  update:
    path: ./overlays/dev
    strategy: Setters
